/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conversormoneda;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author dusha
 */
public class TipoMoneda extends javax.swing.JFrame {

    /**
     * Creates new form TipoMoneda
     */
    private double dato;
    public TipoMoneda() {
        initComponents();
        this.setTitle("Conversor de Monedas");
        Image icono=Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/moneda.png"));
        this.setIconImage(icono);
        this.setLocationRelativeTo(null);
    }
    public void setDato(double dato){
        this.dato = dato;
        //lblDato.setText(Integer.toString(dato));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "De Soles a Dolar", "De Soles a Euro", "De Soles a Libras", "De Soles a Yen", "De Soles a Won Coreano", "De Dolar a Soles", "De Euro a Soles", "De Libra a Soles", "De Yen a Soles", "De Won Coreano a Soles" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 200, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Elige un tipo de Cambio: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 204));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoM.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 440, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        ResultadoM resultadoM = new ResultadoM();
        double res;
        String mensaje;
        String seleccion = (String) jComboBox1.getSelectedItem();
        switch (seleccion) {
        case "De Soles a Dolar":
            res = (dato/3.74);
            mensaje="El Cambio de Soles a Euro";
            resultadoM.setDato(res,mensaje);
            resultadoM.setVisible(true);
            break;
        case "De Soles a Euro":
            res = (dato/4.11);
            mensaje="El Cambio de Soles a Euro";
            resultadoM.setDato(res,mensaje);
            resultadoM.setVisible(true);
            break;
        case "De Soles a Libras":
            res = (dato/4.67);
            mensaje="El Cambio de Soles a Libras";
            resultadoM.setDato(res,mensaje);
            resultadoM.setVisible(true);
            break;
        case "De Soles a Yen":
            res = (dato/0.028);
            mensaje="El Cambio de Soles a Yen";
            resultadoM.setDato(res,mensaje);
            resultadoM.setVisible(true);
            break;
        case "De Soles a Won Coreano":
            res = (dato/0.0028);
            mensaje="El Cambio de Soles a Won Coreano";
            resultadoM.setDato(res,mensaje);
            resultadoM.setVisible(true);
            break;
        case "De Dolar a Soles":
            res = (dato*3.74);
            mensaje="El Cambio de Dolar a Soles";
            resultadoM.setDato(res,mensaje);
            resultadoM.setVisible(true);
            break;
        case "De Euro a Soles":
            res = (dato*4.11);
            mensaje="El Cambio de Euro a Soles";
            resultadoM.setDato(res,mensaje);
            resultadoM.setVisible(true);
            break;
        case "De Libra a Soles":
            res = (dato*4.67);
            mensaje="El Cambio de Libra a Soles";
            resultadoM.setDato(res,mensaje);
            resultadoM.setVisible(true);
            break;
        case "De Yen a Soles":
            res = (dato*0.028);
            mensaje="El Cambio de Yen a Soles";
            resultadoM.setDato(res,mensaje);
            resultadoM.setVisible(true);
            break;
        case "De Won Coreano a Soles":
            res = (dato*0.0028);
            mensaje="El Cambio de Won Coreano a Soles";
            resultadoM.setDato(res,mensaje);
            resultadoM.setVisible(true);
            break;
        default:
            
            break;
        }
        this.dispose();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Moneda moneda = new Moneda();
        moneda.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoMoneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipoMoneda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
