/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conversormoneda;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author dusha
 */
public class TipoTemperatura extends javax.swing.JFrame {

    /**
     * Creates new form TipoTemperatura
     */
    private double dato;
    
    public TipoTemperatura() {
        initComponents();
        this.setTitle("Conversor de Temperatura");
        Image icono=Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/Temperatura.png"));
        this.setIconImage(icono);
        this.setLocationRelativeTo(null);
    }
    public void setDato(double dato){
        this.dato = dato;
        //lblDato.setText(Integer.toString(dato));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Convertir de Celsius a Fahrenheit", "Convertir de Celsius a Kelvin", "Convertir de Fahrenheit a Celsius", "Convertir de Fahrenheit a Kelvin", "Convertir de Kelvin a Celsius", "Convertir de kelvin a Fahrenheit" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 270, 40));

        jButton3.setBackground(new java.awt.Color(255, 255, 204));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Elige una conversion de Temperatura");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        ResultadoT resultadoT = new ResultadoT();
        double res;
        String mensaje;
        String seleccion = (String) jComboBox1.getSelectedItem();
        switch (seleccion) {
        case "Convertir de Celsius a Fahrenheit":
            res = (((9*dato)/5)+32);
            mensaje="La convertir de Celsius a Fahrenheit";
            resultadoT.setDato(res,mensaje);
            resultadoT.setVisible(true);
            break;
        case "Convertir de Celsius a Kelvin":
            res = (dato+273.15);
            mensaje="La convertir de Celsius a Kelvin";
            resultadoT.setDato(res,mensaje);
            resultadoT.setVisible(true);
            break;
        case "Convertir de Fahrenheit a Celsius":
            res = (5*(dato-32))/9;
            mensaje="La convertir de Fahrenheit a Celsius";
            resultadoT.setDato(res,mensaje);
            resultadoT.setVisible(true);
            break;
        case "Convertir de Fahrenheit a Kelvin":
            res = ((5*(dato-32))/9)+273.15;
            mensaje="La convertir de Fahrenheit a Kelvin";
            resultadoT.setDato(res,mensaje);
            resultadoT.setVisible(true);
            break;
        case "Convertir de Kelvin a Celsius":
            res = (dato-273.15);
            mensaje="La convertir de Kelvin a Celsius";
            resultadoT.setDato(res,mensaje);
            resultadoT.setVisible(true);
            break;
        case "Convertir de kelvin a Fahrenheit":
            res = ((9*(dato-273.15))/5)+32;
            mensaje="La convertir de kelvin a Fahrenheit";
            resultadoT.setDato(res,mensaje);
            resultadoT.setVisible(true);
            break;
        default:
            
            break;
        }
        this.dispose();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Temperatura temperatura = new Temperatura();
        temperatura.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipoTemperatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
